#!/bin/sh

keyfile='key_v1.txt';
keysize=16;

echo Generating the Key File $keyfile for FHEv1
java FHEv1 -k $keysize $keyfile
echo Key File $keyfile generated!!!
echo

echo Testing the correctness of encryption and decryption
cipher17=$(java FHEv1 -e 17 $keyfile)
plain17=$(java FHEv1 -d $cipher17 $keyfile)
if [ $plain17 -eq 17 ]; then
   echo The encryption and decryption work correctly!!!
   echo
fi

echo Testing homomorphic addition
cipher_sum=$(java FHEv1 -a $cipher17 -e 18 $keyfile)
plain_sum=$(java FHEv1 -d $cipher_sum $keyfile)
if [ $plain_sum -eq 35 ]; then
   echo The homomorphic addition works correctly!!!
   echo
fi

echo Testing homomorphic multiplication
cipher_product=$(java FHEv1 -m -e 5 -e 7 $keyfile)
plain_product=$(java FHEv1 -d $cipher_product $keyfile)
if [ $plain_product -eq 35 ]; then
   echo The homomorphic multiplication works correctly!!!
   echo
fi

echo Testing the equality test
java FHEv1 -t $cipher_sum $cipher_product $keyfile
java FHEv1 -t -e 34 $cipher_sum $keyfile


echo ---------------------------------------------------------------

keyfile='key_v2.txt';
keysize=96;
w=8;
z=8;

echo Generating the Key File $keyfile for FHEv2
java FHEv2 -k $keysize $w $z $keyfile
echo Key File $keyfile generated!!!
echo

echo Testing the padding
padded=$(java FHEv2 -p 17 $keyfile)
remainder=$(($padded%256))
if [ $remainder -eq 17 ]; then
    echo The padding works correctly!!!
    echo
fi

echo Testing the correctness of encryption and decryption
cipher17=$(java FHEv2 -e 17 $keyfile)
plain17=$(java FHEv2 -d $cipher17 $keyfile)
if [ $plain17 -eq 17 ]; then
   echo The encryption and decryption work correctly!!!
   echo
fi

echo Testing homomorphic addition
cipher_sum=$(java FHEv2 -a $cipher17 -e 18 $keyfile)
plain_sum=$(java FHEv2 -d $cipher_sum $keyfile)
if [ $plain_sum -eq 35 ]; then
   echo The homomorphic addition works correctly!!!
   echo
fi

echo Testing homomorphic multiplication
cipher_product=$(java FHEv2 -m -e 5 -e 7 $keyfile)
plain_product=$(java FHEv2 -d $cipher_product $keyfile)
if [ $plain_product -eq 35 ]; then
   echo The homomorphic multiplication works correctly!!!
   echo
fi


